
import { Photo, PhotoFolder, SessionTemplate } from './types';

const YAPAKA_PHOTOS: Photo[] = [
    { id: 'y001', url: 'https://i.postimg.cc/8z2QLpPs/001.jpg', keywords: ['couple', 'banc', 'discussion'] },
    { id: 'y002', url: 'https://i.postimg.cc/02Hq2GTY/002.jpg', keywords: ['vitrine', 'rouge', 'nuit'] },
    { id: 'y003', url: 'https://i.postimg.cc/jdkrd6p6/003.jpg', keywords: ['travail', 'plans', 'architectes'] },
    { id: 'y004', url: 'https://i.postimg.cc/8PnVPd2W/004.jpg', keywords: ['jeu', 'chantier', 'lego'] },
    { id: 'y005', url: 'https://i.postimg.cc/ncwtcKym/005.jpg', keywords: ['eau', 'sable', 'pieds'] },
    { id: 'y006', url: 'https://i.postimg.cc/651N5Vkv/006.jpg', keywords: ['départ', 'vols', 'aéroport'] },
    { id: 'y007', url: 'https://i.postimg.cc/rFYLFGBt/007.jpg', keywords: ['mémoire', 'chaînes', 'statues'] },
    { id: 'y008', url: 'https://i.postimg.cc/DyYKyQ9m/008.jpg', keywords: ['urbain', 'grue', 'démolition'] },
    { id: 'y009', url: 'https://i.postimg.cc/NfPwf835/009.jpg', keywords: ['fête', 'noël', 'famille'] },
    { id: 'y010', url: 'https://i.postimg.cc/7YQyY1Fh/010.jpg', keywords: ['conflit', 'arrestation', 'police'] },
    { id: 'y011', url: 'https://i.postimg.cc/zXP1Xwsf/011.jpg', keywords: ['préparation', 'cravate', 'mariage'] },
    { id: 'y012', url: 'https://i.postimg.cc/zXP1XwsD/012.jpg', keywords: ['maladie', 'téléphone', 'hôpital'] },
    { id: 'y013', url: 'https://i.postimg.cc/htkWVDPG/013.jpg', keywords: ['spectacle', 'théâtre', 'public'] },
    { id: 'y014', url: 'https://i.postimg.cc/K86StGvc/014.jpg', keywords: ['pleurs', 'enfant', 'père'] },
    { id: 'y015', url: 'https://i.postimg.cc/GhS1hPWd/015.jpg', keywords: ['trafic', 'ville', 'embouteillage'] },
    { id: 'y016', url: 'https://i.postimg.cc/28Xf8dsk/016.jpg', keywords: ['route', 'vitesse', 'panneau'] },
    { id: 'y017', url: 'https://i.postimg.cc/MKr8K0Cw/017.jpg', keywords: ['direction', 'train', 'rails'] },
    { id: 'y018', url: 'https://i.postimg.cc/5NtVVKR2/018.jpg', keywords: ['pollution', 'industrie', 'fumée'] },
    { id: 'y019', url: 'https://i.postimg.cc/HsLggvhH/019.jpg', keywords: ['horizon', 'soleil', 'couchant'] },
    { id: 'y020', url: 'https://i.postimg.cc/TYP66N4R/020.jpg', keywords: ['vieillesse', 'hôpital', 'visite'] },
    { id: 'y021', url: 'https://i.postimg.cc/65QXXbmt/021.jpg', keywords: ['rouge', 'parade', 'noël'] },
    { id: 'y022', url: 'https://i.postimg.cc/TYP66NHH/022.jpg', keywords: ['ressemblance', 'bébé', 'jumeaux'] },
    { id: 'y023', url: 'https://i.postimg.cc/8z2QLpPN/023.jpg', keywords: ['douleur', 'pleurs', 'bébé'] },
    { id: 'y024', url: 'https://i.postimg.cc/P5gs1Xrj/024.jpg', keywords: ['look', 'couple', 'emo'] },
    { id: 'y025', url: 'https://i.postimg.cc/zGsZTzXZ/025.jpg', keywords: ['école', 'écriture', 'fille'] },
    { id: 'y026', url: 'https://i.postimg.cc/YC5KQr2J/026.jpg', keywords: ['liberté', 'saut', 'skate'] },
    { id: 'y027', url: 'https://i.postimg.cc/RV0BBpbD/027.jpg', keywords: ['urbain', 'déchets', 'poubelles'] },
    { id: 'y028', url: 'https://i.postimg.cc/bw7c1yYW/028.jpg', keywords: ['fidélité', 'chien', 'vieux'] },
    { id: 'y029', url: 'https://i.postimg.cc/sD2rrH0K/029.jpg', keywords: ['danger', 'téléphone', 'vélo'] },
    { id: 'y030', url: 'https://i.postimg.cc/nhybqFVP/030.jpg', keywords: ['violence', 'feu', 'émeute'] },
    { id: 'y031', url: 'https://i.postimg.cc/J4hLLYd5/031.jpg', keywords: ['choc', 'nuit', 'explosion'] },
    { id: 'y032', url: 'https://i.postimg.cc/5NtVVKk3/032.jpg', keywords: ['effort', 'saut', 'cheval'] },
    { id: 'y033', url: 'https://i.postimg.cc/jdjbb3kh/033.jpg', keywords: ['insolite', 'ville', 'éléphants'] },
    { id: 'y034', url: 'https://i.postimg.cc/dt0YYNSm/034.jpg', keywords: ['roche', 'nature', 'arche'] },
    { id: 'y035', url: 'https://i.postimg.cc/wjC8DqxW/035.jpg', keywords: ['ventre', 'vie', 'grossesse'] },
    { id: 'y036', url: 'https://i.postimg.cc/05nsh1ZB/036.jpg', keywords: ['groupe', 'joie', 'mariage'] },
    { id: 'y037', url: 'https://i.postimg.cc/wx2pnYFb/037.jpg', keywords: ['famille', 'plateau', 'jeu'] },
    { id: 'y038', url: 'https://i.postimg.cc/T206BvQN/038.jpg', keywords: ['manifestation', 'dérision', 'clown'] },
    { id: 'y039', url: 'https://i.postimg.cc/VkxQXfsD/039.jpg', keywords: ['couple', 'froid', 'pingouins'] },
    { id: 'y040', url: 'https://i.postimg.cc/sfmrbCKn/040.jpg', keywords: ['échecs', 'duel', 'réflexion'] },
    { id: 'y041', url: 'https://i.postimg.cc/dQ6Ygcn6/041.jpg', keywords: ['carton', 'sdf', 'pauvreté'] },
    { id: 'y042', url: 'https://i.postimg.cc/g2XbwXp5/042.jpg', keywords: ['senior', 'vitesse', 'scooter'] },
    { id: 'y043', url: 'https://i.postimg.cc/nhjfsjxw/043.jpg', keywords: ['tendresse', 'bébé', 'père'] },
    { id: 'y044', url: 'https://i.postimg.cc/zD7r4Ypk/044.jpg', keywords: ['espoir', 'lumière', 'fleur'] },
    { id: 'y045', url: 'https://i.postimg.cc/J7xLSCKP/045.jpg', keywords: ['deuil', 'cercueil', 'église'] },
    { id: 'y046', url: 'https://i.postimg.cc/zD7r4YpF/046.jpg', keywords: ['mains', 'peinture', 'couleur'] },
    { id: 'y047', url: 'https://i.postimg.cc/Df6TR35W/047.jpg', keywords: ['femme', 'repos', 'herbe'] },
    { id: 'y048', url: 'https://i.postimg.cc/bYgh4fLt/048.jpg', keywords: ['chocolat', 'enfance', 'pièces'] },
    { id: 'y049', url: 'https://i.postimg.cc/C5cp8bzV/049.jpg', keywords: ['accident', 'urgence', 'secours'] },
    { id: 'y050', url: 'https://i.postimg.cc/fWCN1Q5S/050.jpg', keywords: ['bateau', 'vide', 'échoué'] },
    { id: 'y051', url: 'https://i.postimg.cc/prsMjKyw/051.jpg', keywords: ['fenêtres', 'immeuble', 'urbain'] },
    { id: 'y052', url: 'https://i.postimg.cc/Xqs659XT/052.jpg', keywords: ['musique', 'orchestre', 'groupe'] },
    { id: 'y053', url: 'https://i.postimg.cc/zvxYhT3M/053.jpg', keywords: ['sdf', 'compagnon', 'chien'] },
    { id: 'y054', url: 'https://i.postimg.cc/8cZgvLs0/054.jpg', keywords: ['clocks', 'attente', 'temps'] },
    { id: 'y055', url: 'https://i.postimg.cc/4x7RK7G8/055.jpg', keywords: ['groupe', 'prière', 'foi'] },
    { id: 'y056', url: 'https://i.postimg.cc/3NtQG2Wn/056.jpg', keywords: ['manutention', 'travail', 'charrette'] },
    { id: 'y057', url: 'https://i.postimg.cc/L5xFPjhT/057.jpg', keywords: ['masque', 'mystère', 'anonymat'] },
    { id: 'y058', url: 'https://i.postimg.cc/nr3fmqM1/058.jpg', keywords: ['famille', 'repas', 'dîner'] },
    { id: 'y059', url: 'https://i.postimg.cc/gjgbh3rs/059.jpg', keywords: ['argent', 'médicaments', 'santé'] },
    { id: 'y060', url: 'https://i.postimg.cc/tJBG6F7t/060.jpg', keywords: ['soin', 'peau', 'fragilité'] },
    { id: 'y061', url: 'https://i.postimg.cc/1Xv1FD40/061.jpg', keywords: ['poussettes', 'mouvement', 'ville'] },
    { id: 'y062', url: 'https://i.postimg.cc/yxLCR0WF/062.jpg', keywords: ['femme', 'voile', 'sport'] },
    { id: 'y063', url: 'https://i.postimg.cc/C5cp8bdb/063.jpg', keywords: ['cuisine', 'wok', 'feu'] },
    { id: 'y064', url: 'https://i.postimg.cc/g2XbwXpg/064.jpg', keywords: ['justice', 'loi', 'statue'] },
    { id: 'y065', url: 'https://i.postimg.cc/cCxN6F1c/065.jpg', keywords: ['marché', 'thaïlande', 'vie'] },
    { id: 'y066', url: 'https://i.postimg.cc/kGJdDTMx/066.jpg', keywords: ['linge', 'pauvreté', 'rue'] },
    { id: 'y067', url: 'https://i.postimg.cc/Y0rwjd2z/067.jpg', keywords: ['morpion', 'jeu', 'eau'] },
    { id: 'y068', url: 'https://i.postimg.cc/4yfTnW4V/068.jpg', keywords: ['foot', 'passion', 'pluie'] },
    { id: 'y069', url: 'https://i.postimg.cc/d3sKD5Q3/069.jpg', keywords: ['tristesse', 'isolement', 'sol'] },
    { id: 'y070', url: 'https://i.postimg.cc/J0rWtp7G/070.jpg', keywords: ['téléphone', 'couple', 'silence'] },
    { id: 'y071', url: 'https://i.postimg.cc/WzNPt5p3/071.jpg', keywords: ['vie', 'naissance', 'bébé'] },
    { id: 'y072', url: 'https://i.postimg.cc/gjzPrgcL/072.jpg', keywords: ['soldat', 'lapin', 'contraste'] },
    { id: 'y073', url: 'https://i.postimg.cc/vTYdD08H/073.jpg', keywords: ['direction', 'choix', 'jaune'] },
    { id: 'y074', url: 'https://i.postimg.cc/qqJdg1BB/074.jpg', keywords: ['fauteuil', 'sport', 'basket'] },
    { id: 'y075', url: 'https://i.postimg.cc/fyzhk8WD/075.jpg', keywords: ['parachutisme', 'ciel', 'chute'] },
    { id: 'y076', url: 'https://i.postimg.cc/YCGB4G7x/076.jpg', keywords: ['marelle', 'jeu', 'asphalte'] },
    { id: 'y077', url: 'https://i.postimg.cc/x8fSq6jY/077.jpg', keywords: ['chantier', 'panneau', 'immobilier'] },
    { id: 'y078', url: 'https://i.postimg.cc/FHdXfdvV/078.jpg', keywords: ['sang', 'douche', 'choc'] },
    { id: 'y079', url: 'https://i.postimg.cc/B6c0qr3b/079.jpg', keywords: ['viande', 'étal', 'boucherie'] },
    { id: 'y080', url: 'https://i.postimg.cc/fRtQ3ts7/080.jpg', keywords: ['art', 'gravure', 'roche'] },
    { id: 'y081', url: 'https://i.postimg.cc/0Qds8Tvb/081.jpg', keywords: ['ordinateur', 'lit', 'solitude'] },
    { id: 'y082', url: 'https://i.postimg.cc/Twq6RzxR/082.jpg', keywords: ['anniversaire', 'gâteau', 'joie'] },
    { id: 'y083', url: 'https://i.postimg.cc/Ss7hyB4q/083.jpg', keywords: ['roseaux', 'ciel', 'nature'] },
    { id: 'y084', url: 'https://i.postimg.cc/j5QbspbG/084.jpg', keywords: ['ville', 'nuit', 'lumières'] },
    { id: 'y085', url: 'https://i.postimg.cc/Pxzjtgj9/085.jpg', keywords: ['finance', 'écrans', 'travail'] },
    { id: 'y086', url: 'https://i.postimg.cc/Pxzjtgjc/086.jpg', keywords: ['foule', 'protestation', 'groupe'] },
    { id: 'y087', url: 'https://i.postimg.cc/pTYH2wH0/087.jpg', keywords: ['montagne', 'marche', 'effort'] },
    { id: 'y088', url: 'https://i.postimg.cc/fLjNwGNB/088.jpg', keywords: ['plongée', 'eau', 'bulle'] },
    { id: 'y089', url: 'https://i.postimg.cc/C1HgF3gc/089.jpg', keywords: ['discussion', 'clôture', 'limite'] },
    { id: 'y090', url: 'https://i.postimg.cc/cHNWGsVp/090.jpg', keywords: ['agriculture', 'terre', 'labour'] },
    { id: 'y091', url: 'https://i.postimg.cc/4dTGRJrq/091.jpg', keywords: ['neige', 'froid', 'chemin'] },
    { id: 'y092', url: 'https://i.postimg.cc/XYG6ZGWC/092.jpg', keywords: ['baiser', 'couple', 'amour'] },
    { id: 'y093', url: 'https://i.postimg.cc/PxkHntBc/093.jpg', keywords: ['travail', 'chantier', 'groupe'] },
    { id: 'y094', url: 'https://i.postimg.cc/B6G3fqdz/094.jpg', keywords: ['football', 'jeu', 'enfants'] },
    { id: 'y095', url: 'https://i.postimg.cc/vBdywQpN/095.jpg', keywords: ['écriture', 'papier', 'mains'] },
    { id: 'y096', url: 'https://i.postimg.cc/ydzKCVwj/096.jpg', keywords: ['courrier', 'poste', 'sacs'] },
    { id: 'y097', url: 'https://i.postimg.cc/rmLT28vg/097.jpg', keywords: ['déchets', 'papier', 'chaos'] },
    { id: 'y098', url: 'https://i.postimg.cc/QtrDZXRk/098.jpg', keywords: ['réunion', 'bureau', 'échange'] },
    { id: 'y099', url: 'https://i.postimg.cc/Qd9ZB9DF/099.jpg', keywords: ['temple', 'bouddhisme', 'prière'] },
    { id: 'y100', url: 'https://i.postimg.cc/rmLT28vN/100.jpg', keywords: ['repos', 'famille', 'été'] },
    { id: 'y101', url: 'https://i.postimg.cc/Y9w7BpJW/101.jpg', keywords: ['cimetière', 'recueillement', 'homme'] },
    { id: 'y102', url: 'https://i.postimg.cc/1tZS19LF/102.jpg', keywords: ['gaz', 'bouteille', 'urbain'] },
    { id: 'y103', url: 'https://i.postimg.cc/85VGg1qf/103.jpg', keywords: ['favela', 'ville', 'couleur'] },
    { id: 'y104', url: 'https://i.postimg.cc/k4dCPnkt/104.jpg', keywords: ['poupée', 'enfance', 'jouet'] },
    { id: 'y105', url: 'https://i.postimg.cc/xdmQZkFL/105.jpg', keywords: ['âne', 'charrette', 'transport'] },
    { id: 'y106', url: 'https://i.postimg.cc/xdmQZkFK/106.jpg', keywords: ['portage', 'bébé', 'maman'] },
    { id: 'y107', url: 'https://i.postimg.cc/W4ZVyDfZ/107.jpg', keywords: ['classe', 'attente', 'école'] },
    { id: 'y108', url: 'https://i.postimg.cc/YSF7P4yW/108.jpg', keywords: ['reflet', 'calme', 'eau'] },
    { id: 'y109', url: 'https://i.postimg.cc/0NSv46Hy/109.jpg', keywords: ['repas', 'rue', 'partage'] },
    { id: 'y110', url: 'https://i.postimg.cc/FKSv6fnK/110.jpg', keywords: ['école', 'amitié', 'enfants'] },
    { id: 'y111', url: 'https://i.postimg.cc/wBNzrtb1/111.jpg', keywords: ['rizière', 'nature', 'travail'] },
    { id: 'y112', url: 'https://i.postimg.cc/wBNzrtbq/112.jpg', keywords: ['fontaine', 'enfants', 'eau'] },
];

const PEDAGOGIE_PHOTOS: Photo[] = [
    { id: 'f001', url: 'https://i.postimg.cc/MT8Y74Q8/1496519447.jpg', keywords: ['groupe', 'travail'] },
    { id: 'f002', url: 'https://i.postimg.cc/9f9pqVrC/19-1-nf-formation-agro-gms.jpg', keywords: ['agro', 'formation'] },
    { id: 'f003', url: 'https://i.postimg.cc/JhXqBmG4/219953747-small.jpg', keywords: ['microscopique', 'recherche'] },
    { id: 'f004', url: 'https://i.postimg.cc/qRdGsY3V/22914.jpg', keywords: ['bureau', 'technique'] },
    { id: 'f005', url: 'https://i.postimg.cc/mr9wFRtL/26-jerash-xl.jpg', keywords: ['histoire', 'site'] },
    { id: 'f006', url: 'https://i.postimg.cc/zfhjR5VJ/4-enfants.jpg', keywords: ['enfance', 'partage'] },
    { id: 'f007', url: 'https://i.postimg.cc/B6GCTyKW/582-Troopers-receiving-information-about-next-competition.jpg', keywords: ['briefing', 'militaire'] },
    { id: 'f008', url: 'https://i.postimg.cc/N0X4rY5G/86206235-small.jpg', keywords: ['abstrait', 'bleu'] },
    { id: 'f009', url: 'https://i.postimg.cc/d1K92XyY/Affiche-egalite2.jpg', keywords: ['égalité', 'affiche'] },
    { id: 'f010', url: 'https://i.postimg.cc/C1V4GtqY/afficher-image.jpg', keywords: ['image', 'cadre'] },
    { id: 'f011', url: 'https://i.postimg.cc/hjq0LwdD/alex.jpg', keywords: ['portrait', 'jeune'] },
    { id: 'f012', url: 'https://i.postimg.cc/tTHz3fxb/Alex-Grigny-de-Castro-Sojourner-Large.jpg', keywords: ['astronomie', 'robot'] },
    { id: 'f013', url: 'https://i.postimg.cc/zB1kCMgq/alex-ii-imp-maria-alex-25marriage.jpg', keywords: ['mariage', 'impérial'] },
    { id: 'f014', url: 'https://i.postimg.cc/ydzTm5ZV/aleximg.jpg', keywords: ['portrait'] },
    { id: 'f015', url: 'https://i.postimg.cc/tTHz3fxR/Animation-magasin.jpg', keywords: ['magasin', 'commerce'] },
    { id: 'f016', url: 'https://i.postimg.cc/wvdkXPmT/ap17-72-H-314.jpg', keywords: ['espace', 'mission'] },
    { id: 'f017', url: 'https://i.postimg.cc/pTtBf7FL/Artistes-140-2002-06-5-musiciens-copier.jpg', keywords: ['musiciens', 'groupe'] },
    { id: 'f018', url: 'https://i.postimg.cc/tTHz3fxg/atf19.jpg', keywords: ['aviation', 'technique'] },
    { id: 'f019', url: 'https://i.postimg.cc/sXRJY8h1/ballade-cormet-rosseland-aou00.jpg', keywords: ['montagne', 'marche'] },
    { id: 'f020', url: 'https://i.postimg.cc/cHNcRjnC/bassiak.jpg', keywords: ['afrique', 'portrait'] },
    { id: 'f021', url: 'https://i.postimg.cc/ZRhL8gdC/berger.jpg', keywords: ['berger', 'moutons'] },
    { id: 'f022', url: 'https://i.postimg.cc/d1K92Xyk/bomba01.jpg', keywords: ['usine', 'industrie'] },
    { id: 'f023', url: 'https://i.postimg.cc/TwXcVSD5/boulanger-121-tcm41-7294.jpg', keywords: ['boulanger', 'métier'] },
    { id: 'f024', url: 'https://i.postimg.cc/fLhvcF90/c172.jpg', keywords: ['avion', 'pilotage'] },
    { id: 'f025', url: 'https://i.postimg.cc/j5rhH977/chef-M-Stadtlander.jpg', keywords: ['gastronomie', 'chef'] },
    { id: 'f026', url: 'https://i.postimg.cc/DZKcrDXs/competition-LFS-2005-(67).jpg', keywords: ['sport', 'école'] },
    { id: 'f027', url: 'https://i.postimg.cc/mDGSYqHC/conducteur.jpg', keywords: ['conduite', 'camion'] },
    { id: 'f028', url: 'https://i.postimg.cc/C1V4GtqG/CONVAR93.jpg', keywords: ['réunion', 'congrès'] },
    { id: 'f029', url: 'https://i.postimg.cc/wvdkXPmh/Cours-Vigneux.jpg', keywords: ['cours', 'enseignement'] },
    { id: 'f030', url: 'https://i.postimg.cc/3RCFnBX4/cuisine.jpg', keywords: ['cuisine', 'tradition'] },
    { id: 'f031', url: 'https://i.postimg.cc/C1HsmNGZ/danse.jpg', keywords: ['ballet', 'danse'] },
    { id: 'f032', url: 'https://i.postimg.cc/HxCtwKy0/digitaldrucke1.jpg', keywords: ['impression', 'numerique'] },
    { id: 'f033', url: 'https://i.postimg.cc/NM7kp465/divan-japonais-maitre-web.jpg', keywords: ['affiche', 'art'] },
    { id: 'f034', url: 'https://i.postimg.cc/76MnmV32/diver.jpg', keywords: ['plongée', 'mer'] },
    { id: 'f035', url: 'https://i.postimg.cc/LXB3NTtZ/dre117.jpg', keywords: ['électricité', 'câbles'] },
    { id: 'f036', url: 'https://i.postimg.cc/NM7kp46X/DSCN3859.jpg', keywords: ['nature', 'macrophotographie'] },
    { id: 'f037', url: 'https://i.postimg.cc/nzYG0k47/equipe-spv-pt.jpg', keywords: ['pompiers', 'équipe'] },
    { id: 'f038', url: 'https://i.postimg.cc/wvcQ0VXL/Ernest-Lavisse14-1.jpg', keywords: ['école', 'ancienne'] },
    { id: 'f039', url: 'https://i.postimg.cc/Jnc5PqN3/escalier.jpg', keywords: ['monument', 'escalier'] },
    { id: 'f040', url: 'https://i.postimg.cc/sX94wcYp/forme.jpg', keywords: ['géométrie', 'design'] },
    { id: 'f041', url: 'https://i.postimg.cc/fLjfBKcc/fouille.jpg', keywords: ['archéologie', 'histoire'] },
    { id: 'f042', url: 'https://i.postimg.cc/C1HsmNGH/francais.jpg', keywords: ['langue', 'écriture'] },
    { id: 'f043', url: 'https://i.postimg.cc/QtkJ0bQ4/garde.jpg', keywords: ['sentinelle', 'uniforme'] },
    { id: 'f044', url: 'https://i.postimg.cc/sX94wcYK/grandeur.jpg', keywords: ['paysage', 'vastitude'] },
    { id: 'f045', url: 'https://i.postimg.cc/4dbQB561/H2H19Endings-Mike.jpg', keywords: ['mains', 'relais'] },
    { id: 'f046', url: 'https://i.postimg.cc/mDNy8wYK/HHTRUMP.jpg', keywords: ['trompette', 'jazz'] },
    { id: 'f047', url: 'https://i.postimg.cc/zBSF0jCM/imag12mare.jpg', keywords: ['plage', 'vacances'] },
    { id: 'f048', url: 'https://i.postimg.cc/85VbR36L/image.jpg', keywords: ['paysage', 'lac'] },
    { id: 'f049', url: 'https://i.postimg.cc/qRXxjLs9/Image128.gif', keywords: ['ordinateur', 'vintage'] },
    { id: 'f050', url: 'https://i.postimg.cc/bJH93TxF/Image7.jpg', keywords: ['microscope', 'biologie'] },
    { id: 'f051', url: 'https://i.postimg.cc/T1dqSD0C/Initiation-escalade-Pont-de-Montvert.jpg', keywords: ['escalade', 'sport'] },
    { id: 'f052', url: 'https://i.postimg.cc/kGJFZbsT/kapalicarsi-musique01.jpg', keywords: ['musique', 'traditionnelle'] },
    { id: 'f053', url: 'https://i.postimg.cc/bJH93Tx7/Kwi-Krimp-600.jpg', keywords: ['outil', 'industrie'] },
    { id: 'f054', url: 'https://i.postimg.cc/XqjchCLH/Learning-to-Surf.jpg', keywords: ['surf', 'mer'] },
    { id: 'f055', url: 'https://i.postimg.cc/GtLJNyKS/lecture.jpg', keywords: ['lecture', 'étudiant'] },
    { id: 'f056', url: 'https://i.postimg.cc/d3smXy6X/liqing-pool.jpg', keywords: ['billard', 'loisir'] },
    { id: 'f057', url: 'https://i.postimg.cc/RhSQ8HdD/Livre.jpg', keywords: ['livre', 'ouvert'] },
    { id: 'f058', url: 'https://i.postimg.cc/D0vdDX6H/livres.jpg', keywords: ['bibliothèque', 'culture'] },
    { id: 'f059', url: 'https://i.postimg.cc/HnY4KyzF/LSM-ribaud.jpg', keywords: ['noir et blanc', 'portrait'] },
    { id: 'f060', url: 'https://i.postimg.cc/fyzjF9C6/lun.jpg', keywords: ['lune', 'astronomie'] },
    { id: 'f061', url: 'https://i.postimg.cc/fyzjF9CG/maitre.jpg', keywords: ['enseignant', 'autorité'] },
    { id: 'f062', url: 'https://i.postimg.cc/T1dqSDQ8/maitre-tamura.jpg', keywords: ['arts martiaux', 'maître'] },
    { id: 'f063', url: 'https://i.postimg.cc/cCxMjnTd/manuel.jpg', keywords: ['manuel', 'apprentissage'] },
    { id: 'f064', url: 'https://i.postimg.cc/fyzjF95s/metre-etalon.jpg', keywords: ['mesure', 'règle'] },
    { id: 'f065', url: 'https://i.postimg.cc/mkLNqHVG/navette.jpg', keywords: ['navette', 'espace'] },
    { id: 'f066', url: 'https://i.postimg.cc/x8fy7zgY/nom3cut.jpg', keywords: ['portrait', 'découpé'] },
    { id: 'f067', url: 'https://i.postimg.cc/FzrgqLGs/Panneau-vue.gif', keywords: ['vue', 'test'] },
    { id: 'f068', url: 'https://i.postimg.cc/KjGrVMQ8/panneaux-thai.jpg', keywords: ['thaïlande', 'signalisation'] },
    { id: 'f069', url: 'https://i.postimg.cc/T1dqSDQP/part02.jpg', keywords: ['partition', 'musique'] },
    { id: 'f070', url: 'https://i.postimg.cc/yx1X5Znd/paulrobert.jpg', keywords: ['dictionnaire', 'référence'] },
    { id: 'f071', url: 'https://i.postimg.cc/0jkd3wZj/pedagogie-active.jpg', keywords: ['pédagogie', 'collaboration'] },
    { id: 'f072', url: 'https://i.postimg.cc/j2MQrSkd/photolangage.jpg', keywords: ['mains', 'interaction'] },
    { id: 'f073', url: 'https://i.postimg.cc/mkLNqHVh/Porte5.jpg', keywords: ['porte', 'bois'] },
    { id: 'f074', url: 'https://i.postimg.cc/1XvcZ3YP/prec-1.jpg', keywords: ['travail', 'précis'] },
    { id: 'f075', url: 'https://i.postimg.cc/GtLJNyzH/precision.jpg', keywords: ['horlogerie', 'précision'] },
    { id: 'f076', url: 'https://i.postimg.cc/qq1XdvZp/rencontre-cle0145ba-3.jpg', keywords: ['poignée de main', 'accord'] },
    { id: 'f077', url: 'https://i.postimg.cc/3NtCHxbw/riziere6.jpg', keywords: ['rizière', 'agriculture'] },
    { id: 'f078', url: 'https://i.postimg.cc/ZnwFh5DY/rythmeos.jpg', keywords: ['vibration', 'physique'] },
    { id: 'f079', url: 'https://i.postimg.cc/5ysqM2k2/salle-permanence.jpg', keywords: ['études', 'école'] },
    { id: 'f080', url: 'https://i.postimg.cc/MH9b8prH/schmids3c.jpg', keywords: ['visage', 'expression'] },
    { id: 'f081', url: 'https://i.postimg.cc/cCFMNL56/sesia-mollia-sco-(14).jpg', keywords: ['paysage', 'rivière'] },
    { id: 'f082', url: 'https://i.postimg.cc/Y0dfwCyG/SIEBUS.jpg', keywords: ['transport', 'urbain'] },
    { id: 'f083', url: 'https://i.postimg.cc/Y0dfwCyh/solitude.jpg', keywords: ['isole', 'homme'] },
    { id: 'f084', url: 'https://i.postimg.cc/yxLXz8rD/suivi-traces.jpg', keywords: ['empreintes', 'neige'] },
    { id: 'f085', url: 'https://i.postimg.cc/6qMLNp17/Surgeons-Looking-at-Patient.jpg', keywords: ['chirurgie', 'hôpital'] },
    { id: 'f086', url: 'https://i.postimg.cc/x86yS1FN/tableau-jeu.jpg', keywords: ['jeu', 'scolaire'] },
    { id: 'f087', url: 'https://i.postimg.cc/2y0FfSXB/testing-6sn7gt.gif', keywords: ['test', 'électronique'] },
    { id: 'f088', url: 'https://i.postimg.cc/RhgQzZbw/thai-corn-cake-david-hand.jpg', keywords: ['gastronomie', 'marché'] },
    { id: 'f089', url: 'https://i.postimg.cc/SRg7pxtC/Tourbillon-de-sable-img4904.jpg', keywords: ['désert', 'vent'] },
    { id: 'f090', url: 'https://i.postimg.cc/SRg7pxtM/tourbillon10.jpg', keywords: ['mouvement', 'tourbillon'] },
    { id: 'f091', url: 'https://i.postimg.cc/J0pcWzdN/tres-ranchos-canoe.jpg', keywords: ['canoë', 'aventure'] },
    { id: 'f092', url: 'https://i.postimg.cc/wMwcdjbh/tribunal.jpg', keywords: ['loi', 'justice'] },
    { id: 'f093', url: 'https://i.postimg.cc/Y0dfwCyf/tu-dresden-slub-lesesaal-studenten-02.jpg', keywords: ['université', 'étude'] },
    { id: 'f094', url: 'https://i.postimg.cc/BbmcGnwB/union10.jpg', keywords: ['union', 'mains'] },
    { id: 'f095', url: 'https://i.postimg.cc/90LtjQNB/vendanges.gif', keywords: ['vigne', 'tradition'] },
    { id: 'f096', url: 'https://i.postimg.cc/J0pcWzdx/Web-Contest1.jpg', keywords: ['internet', 'réseau'] },
    { id: 'f097', url: 'https://i.postimg.cc/yxLXz8rP/yak50panel.jpg', keywords: ['cockpit', 'instrument'] },
    { id: 'f098', url: 'https://i.postimg.cc/QCfkrdnS/zdrag-full.jpg', keywords: ['abstrait', 'graphisme'] },
    { id: 'f099', url: 'https://i.postimg.cc/GpDQsrHb/zenith.jpg', keywords: ['soleil', 'ciel'] },
];

export const PHOTO_FOLDERS: PhotoFolder[] = [
  {
    id: 'yapaka',
    name: 'Yapaka - Photo Expression',
    description: 'La collection intégrale de 112 photos Yapaka pour libérer la parole.',
    cover: 'https://i.postimg.cc/wBNzrtbq/112.jpg',
    photos: YAPAKA_PHOTOS
  },
  {
    id: 'pedagogie',
    name: 'Pédagogie & Monde',
    description: 'Une nouvelle sélection d\'images axée sur l\'apprentissage, le travail et la découverte.',
    cover: 'https://i.postimg.cc/0jkd3wZj/pedagogie-active.jpg',
    photos: PEDAGOGIE_PHOTOS
  }
];

export const SESSION_TEMPLATES: SessionTemplate[] = [
    {
        id: 'libre',
        title: 'Séance Libre',
        description: 'Créez votre séance à partir de la collection Yapaka.',
        question: 'Choisissez une image qui vous interpelle...',
        defaultFolderId: 'yapaka',
        icon: 'Edit3'
    },
    {
        id: 'meteo',
        title: 'Météo Intérieure',
        description: 'Démarrer une réunion avec la collection Yapaka.',
        question: 'Quelle image correspond le mieux à votre état d\'esprit actuel ?',
        defaultFolderId: 'yapaka',
        icon: 'Sun'
    }
];

export const MOCK_PHOTOS = YAPAKA_PHOTOS;
export const INITIAL_SESSION_CODE = "XJ9-2B";
