
import { Photo, PhotoFolder, SessionTemplate } from './types';

const YAPAKA_PHOTOS: Photo[] = [
    { id: 'y001', url: 'https://i.postimg.cc/8z2QLpPs/001.jpg', keywords: ['couple', 'banc', 'discussion'] },
    { id: 'y002', url: 'https://i.postimg.cc/02Hq2GTY/002.jpg', keywords: ['vitrine', 'rouge', 'nuit'] },
    { id: 'y003', url: 'https://i.postimg.cc/jdkrd6p6/003.jpg', keywords: ['travail', 'plans', 'architectes'] },
    { id: 'y004', url: 'https://i.postimg.cc/8PnVPd2W/004.jpg', keywords: ['jeu', 'chantier', 'lego'] },
    { id: 'y005', url: 'https://i.postimg.cc/ncwtcKym/005.jpg', keywords: ['eau', 'sable', 'pieds'] },
    { id: 'y006', url: 'https://i.postimg.cc/651N5Vkv/006.jpg', keywords: ['départ', 'vols', 'aéroport'] },
    { id: 'y007', url: 'https://i.postimg.cc/rFYLFGBt/007.jpg', keywords: ['mémoire', 'chaînes', 'statues'] },
    { id: 'y008', url: 'https://i.postimg.cc/DyYKyQ9m/008.jpg', keywords: ['urbain', 'grue', 'démolition'] },
    { id: 'y009', url: 'https://i.postimg.cc/NfPwf835/009.jpg', keywords: ['fête', 'noël', 'famille'] },
    { id: 'y010', url: 'https://i.postimg.cc/7YQyY1Fh/010.jpg', keywords: ['conflit', 'arrestation', 'police'] },
    { id: 'y011', url: 'https://i.postimg.cc/zXP1Xwsf/011.jpg', keywords: ['préparation', 'cravate', 'mariage'] },
    { id: 'y012', url: 'https://i.postimg.cc/zXP1XwsD/012.jpg', keywords: ['maladie', 'téléphone', 'hôpital'] },
    { id: 'y013', url: 'https://i.postimg.cc/htkWVDPG/013.jpg', keywords: ['spectacle', 'théâtre', 'public'] },
    { id: 'y014', url: 'https://i.postimg.cc/K86StGvc/014.jpg', keywords: ['pleurs', 'enfant', 'père'] },
    { id: 'y015', url: 'https://i.postimg.cc/GhS1hPWd/015.jpg', keywords: ['trafic', 'ville', 'embouteillage'] },
    { id: 'y016', url: 'https://i.postimg.cc/28Xf8dsk/016.jpg', keywords: ['route', 'vitesse', 'panneau'] },
    { id: 'y017', url: 'https://i.postimg.cc/MKr8K0Cw/017.jpg', keywords: ['direction', 'train', 'rails'] },
    { id: 'y018', url: 'https://i.postimg.cc/5NtVVKR2/018.jpg', keywords: ['pollution', 'industrie', 'fumée'] },
    { id: 'y019', url: 'https://i.postimg.cc/HsLggvhH/019.jpg', keywords: ['horizon', 'soleil', 'couchant'] },
    { id: 'y020', url: 'https://i.postimg.cc/TYP66N4R/020.jpg', keywords: ['vieillesse', 'hôpital', 'visite'] },
    { id: 'y021', url: 'https://i.postimg.cc/65QXXbmt/021.jpg', keywords: ['rouge', 'parade', 'noël'] },
    { id: 'y022', url: 'https://i.postimg.cc/TYP66NHH/022.jpg', keywords: ['ressemblance', 'bébé', 'jumeaux'] },
    { id: 'y023', url: 'https://i.postimg.cc/8z2QLpPN/023.jpg', keywords: ['douleur', 'pleurs', 'bébé'] },
    { id: 'y024', url: 'https://i.postimg.cc/P5gs1Xrj/024.jpg', keywords: ['look', 'couple', 'emo'] },
    { id: 'y025', url: 'https://i.postimg.cc/zGsZTzXZ/025.jpg', keywords: ['école', 'écriture', 'fille'] },
    { id: 'y026', url: 'https://i.postimg.cc/YC5KQr2J/026.jpg', keywords: ['liberté', 'saut', 'skate'] },
    { id: 'y027', url: 'https://i.postimg.cc/RV0BBpbD/027.jpg', keywords: ['urbain', 'déchets', 'poubelles'] },
    { id: 'y028', url: 'https://i.postimg.cc/bw7c1yYW/028.jpg', keywords: ['fidélité', 'chien', 'vieux'] },
    { id: 'y029', url: 'https://i.postimg.cc/sD2rrH0K/029.jpg', keywords: ['danger', 'téléphone', 'vélo'] },
    { id: 'y030', url: 'https://i.postimg.cc/nhybqFVP/030.jpg', keywords: ['violence', 'feu', 'émeute'] },
    { id: 'y031', url: 'https://i.postimg.cc/J4hLLYd5/031.jpg', keywords: ['choc', 'nuit', 'explosion'] },
    { id: 'y032', url: 'https://i.postimg.cc/5NtVVKk3/032.jpg', keywords: ['effort', 'saut', 'cheval'] },
    { id: 'y033', url: 'https://i.postimg.cc/jdjbb3kh/033.jpg', keywords: ['insolite', 'ville', 'éléphants'] },
    { id: 'y034', url: 'https://i.postimg.cc/dt0YYNSm/034.jpg', keywords: ['roche', 'nature', 'arche'] },
    { id: 'y035', url: 'https://i.postimg.cc/wjC8DqxW/035.jpg', keywords: ['ventre', 'vie', 'grossesse'] },
    { id: 'y036', url: 'https://i.postimg.cc/05nsh1ZB/036.jpg', keywords: ['groupe', 'joie', 'mariage'] },
    { id: 'y037', url: 'https://i.postimg.cc/wx2pnYFb/037.jpg', keywords: ['famille', 'plateau', 'jeu'] },
    { id: 'y038', url: 'https://i.postimg.cc/T206BvQN/038.jpg', keywords: ['manifestation', 'dérision', 'clown'] },
    { id: 'y039', url: 'https://i.postimg.cc/VkxQXfsD/039.jpg', keywords: ['couple', 'froid', 'pingouins'] },
    { id: 'y040', url: 'https://i.postimg.cc/sfmrbCKn/040.jpg', keywords: ['échecs', 'duel', 'réflexion'] },
    { id: 'y041', url: 'https://i.postimg.cc/dQ6Ygcn6/041.jpg', keywords: ['carton', 'sdf', 'pauvreté'] },
    { id: 'y042', url: 'https://i.postimg.cc/g2XbwXp5/042.jpg', keywords: ['senior', 'vitesse', 'scooter'] },
    { id: 'y043', url: 'https://i.postimg.cc/nhjfsjxw/043.jpg', keywords: ['tendresse', 'bébé', 'père'] },
    { id: 'y044', url: 'https://i.postimg.cc/zD7r4Ypk/044.jpg', keywords: ['espoir', 'lumière', 'fleur'] },
    { id: 'y045', url: 'https://i.postimg.cc/J7xLSCKP/045.jpg', keywords: ['deuil', 'cercueil', 'église'] },
    { id: 'y046', url: 'https://i.postimg.cc/zD7r4YpF/046.jpg', keywords: ['mains', 'peinture', 'couleur'] },
    { id: 'y047', url: 'https://i.postimg.cc/Df6TR35W/047.jpg', keywords: ['femme', 'repos', 'herbe'] },
    { id: 'y048', url: 'https://i.postimg.cc/bYgh4fLt/048.jpg', keywords: ['chocolat', 'enfance', 'pièces'] },
    { id: 'y049', url: 'https://i.postimg.cc/C5cp8bzV/049.jpg', keywords: ['accident', 'urgence', 'secours'] },
    { id: 'y050', url: 'https://i.postimg.cc/fWCN1Q5S/050.jpg', keywords: ['bateau', 'vide', 'échoué'] },
    { id: 'y051', url: 'https://i.postimg.cc/prsMjKyw/051.jpg', keywords: ['fenêtres', 'immeuble', 'urbain'] },
    { id: 'y052', url: 'https://i.postimg.cc/Xqs659XT/052.jpg', keywords: ['musique', 'orchestre', 'groupe'] },
    { id: 'y053', url: 'https://i.postimg.cc/zvxYhT3M/053.jpg', keywords: ['sdf', 'compagnon', 'chien'] },
    { id: 'y054', url: 'https://i.postimg.cc/8cZgvLs0/054.jpg', keywords: ['clocks', 'attente', 'temps'] },
    { id: 'y055', url: 'https://i.postimg.cc/4x7RK7G8/055.jpg', keywords: ['groupe', 'prière', 'foi'] },
    { id: 'y056', url: 'https://i.postimg.cc/3NtQG2Wn/056.jpg', keywords: ['manutention', 'travail', 'charrette'] },
    { id: 'y057', url: 'https://i.postimg.cc/L5xFPjhT/057.jpg', keywords: ['masque', 'mystère', 'anonymat'] },
    { id: 'y058', url: 'https://i.postimg.cc/nr3fmqM1/058.jpg', keywords: ['famille', 'repas', 'dîner'] },
    { id: 'y059', url: 'https://i.postimg.cc/gjgbh3rs/059.jpg', keywords: ['argent', 'médicaments', 'santé'] },
    { id: 'y060', url: 'https://i.postimg.cc/tJBG6F7t/060.jpg', keywords: ['soin', 'peau', 'fragilité'] },
    { id: 'y061', url: 'https://i.postimg.cc/1Xv1FD40/061.jpg', keywords: ['poussettes', 'mouvement', 'ville'] },
    { id: 'y062', url: 'https://i.postimg.cc/yxLCR0WF/062.jpg', keywords: ['femme', 'voile', 'sport'] },
    { id: 'y063', url: 'https://i.postimg.cc/C5cp8bdb/063.jpg', keywords: ['cuisine', 'wok', 'feu'] },
    { id: 'y064', url: 'https://i.postimg.cc/g2XbwXpg/064.jpg', keywords: ['justice', 'loi', 'statue'] },
    { id: 'y065', url: 'https://i.postimg.cc/cCxN6F1c/065.jpg', keywords: ['marché', 'thaïlande', 'vie'] },
    { id: 'y066', url: 'https://i.postimg.cc/kGJdDTMx/066.jpg', keywords: ['linge', 'pauvreté', 'rue'] },
    { id: 'y067', url: 'https://i.postimg.cc/Y0rwjd2z/067.jpg', keywords: ['morpion', 'jeu', 'eau'] },
    { id: 'y068', url: 'https://i.postimg.cc/4yfTnW4V/068.jpg', keywords: ['foot', 'passion', 'pluie'] },
    { id: 'y069', url: 'https://i.postimg.cc/d3sKD5Q3/069.jpg', keywords: ['tristesse', 'isolement', 'sol'] },
    { id: 'y070', url: 'https://i.postimg.cc/J0rWtp7G/070.jpg', keywords: ['téléphone', 'couple', 'silence'] },
    { id: 'y071', url: 'https://i.postimg.cc/WzNPt5p3/071.jpg', keywords: ['vie', 'naissance', 'bébé'] },
    { id: 'y072', url: 'https://i.postimg.cc/gjzPrgcL/072.jpg', keywords: ['soldat', 'lapin', 'contraste'] },
    { id: 'y073', url: 'https://i.postimg.cc/vTYdD08H/073.jpg', keywords: ['direction', 'choix', 'jaune'] },
    { id: 'y074', url: 'https://i.postimg.cc/qqJdg1BB/074.jpg', keywords: ['fauteuil', 'sport', 'basket'] },
    { id: 'y075', url: 'https://i.postimg.cc/fyzhk8WD/075.jpg', keywords: ['parachutisme', 'ciel', 'chute'] },
    { id: 'y076', url: 'https://i.postimg.cc/YCGB4G7x/076.jpg', keywords: ['marelle', 'jeu', 'asphalte'] },
    { id: 'y077', url: 'https://i.postimg.cc/x8fSq6jY/077.jpg', keywords: ['chantier', 'panneau', 'immobilier'] },
    { id: 'y078', url: 'https://i.postimg.cc/FHdXfdvV/078.jpg', keywords: ['sang', 'douche', 'choc'] },
    { id: 'y079', url: 'https://i.postimg.cc/B6c0qr3b/079.jpg', keywords: ['viande', 'étal', 'boucherie'] },
    { id: 'y080', url: 'https://i.postimg.cc/fRtQ3ts7/080.jpg', keywords: ['art', 'gravure', 'roche'] },
    { id: 'y081', url: 'https://i.postimg.cc/0Qds8Tvb/081.jpg', keywords: ['ordinateur', 'lit', 'solitude'] },
    { id: 'y082', url: 'https://i.postimg.cc/Twq6RzxR/082.jpg', keywords: ['anniversaire', 'gâteau', 'joie'] },
    { id: 'y083', url: 'https://i.postimg.cc/Ss7hyB4q/083.jpg', keywords: ['roseaux', 'ciel', 'nature'] },
    { id: 'y084', url: 'https://i.postimg.cc/j5QbspbG/084.jpg', keywords: ['ville', 'nuit', 'lumières'] },
    { id: 'y085', url: 'https://i.postimg.cc/Pxzjtgj9/085.jpg', keywords: ['finance', 'écrans', 'travail'] },
    { id: 'y086', url: 'https://i.postimg.cc/Pxzjtgjc/086.jpg', keywords: ['foule', 'protestation', 'groupe'] },
    { id: 'y087', url: 'https://i.postimg.cc/pTYH2wH0/087.jpg', keywords: ['montagne', 'marche', 'effort'] },
    { id: 'y088', url: 'https://i.postimg.cc/fLjNwGNB/088.jpg', keywords: ['plongée', 'eau', 'bulle'] },
    { id: 'y089', url: 'https://i.postimg.cc/C1HgF3gc/089.jpg', keywords: ['discussion', 'clôture', 'limite'] },
    { id: 'y090', url: 'https://i.postimg.cc/cHNWGsVp/090.jpg', keywords: ['agriculture', 'terre', 'labour'] },
    { id: 'y091', url: 'https://i.postimg.cc/4dTGRJrq/091.jpg', keywords: ['neige', 'froid', 'chemin'] },
    { id: 'y092', url: 'https://i.postimg.cc/XYG6ZGWC/092.jpg', keywords: ['baiser', 'couple', 'amour'] },
    { id: 'y093', url: 'https://i.postimg.cc/PxkHntBc/093.jpg', keywords: ['travail', 'chantier', 'groupe'] },
    { id: 'y094', url: 'https://i.postimg.cc/B6G3fqdz/094.jpg', keywords: ['football', 'jeu', 'enfants'] },
    { id: 'y095', url: 'https://i.postimg.cc/vBdywQpN/095.jpg', keywords: ['écriture', 'papier', 'mains'] },
    { id: 'y096', url: 'https://i.postimg.cc/ydzKCVwj/096.jpg', keywords: ['courrier', 'poste', 'sacs'] },
    { id: 'y097', url: 'https://i.postimg.cc/rmLT28vg/097.jpg', keywords: ['déchets', 'papier', 'chaos'] },
    { id: 'y098', url: 'https://i.postimg.cc/QtrDZXRk/098.jpg', keywords: ['réunion', 'bureau', 'échange'] },
    { id: 'y099', url: 'https://i.postimg.cc/Qd9ZB9DF/099.jpg', keywords: ['temple', 'bouddhisme', 'prière'] },
    { id: 'y100', url: 'https://i.postimg.cc/rmLT28vN/100.jpg', keywords: ['repos', 'famille', 'été'] },
    { id: 'y101', url: 'https://i.postimg.cc/Y9w7BpJW/101.jpg', keywords: ['cimetière', 'recueillement', 'homme'] },
    { id: 'y102', url: 'https://i.postimg.cc/1tZS19LF/102.jpg', keywords: ['gaz', 'bouteille', 'urbain'] },
    { id: 'y103', url: 'https://i.postimg.cc/85VGg1qf/103.jpg', keywords: ['favela', 'ville', 'couleur'] },
    { id: 'y104', url: 'https://i.postimg.cc/k4dCPnkt/104.jpg', keywords: ['poupée', 'enfance', 'jouet'] },
    { id: 'y105', url: 'https://i.postimg.cc/xdmQZkFL/105.jpg', keywords: ['âne', 'charrette', 'transport'] },
    { id: 'y106', url: 'https://i.postimg.cc/xdmQZkFK/106.jpg', keywords: ['portage', 'bébé', 'maman'] },
    { id: 'y107', url: 'https://i.postimg.cc/W4ZVyDfZ/107.jpg', keywords: ['classe', 'attente', 'école'] },
    { id: 'y108', url: 'https://i.postimg.cc/YSF7P4yW/108.jpg', keywords: ['reflet', 'calme', 'eau'] },
    { id: 'y109', url: 'https://i.postimg.cc/0NSv46Hy/109.jpg', keywords: ['repas', 'rue', 'partage'] },
    { id: 'y110', url: 'https://i.postimg.cc/FKSv6fnK/110.jpg', keywords: ['école', 'amitié', 'enfants'] },
    { id: 'y111', url: 'https://i.postimg.cc/wBNzrtb1/111.jpg', keywords: ['rizière', 'nature', 'travail'] },
    { id: 'y112', url: 'https://i.postimg.cc/wBNzrtbq/112.jpg', keywords: ['fontaine', 'enfants', 'eau'] },
];

const INSPIRATION_PHOTOS: Photo[] = [
    { id: 'n001', url: 'https://i.postimg.cc/TYkDNNp7/Alpsee-Schwangau-Germany-by-Rachel-Davis-via-unsplash-com.jpg', keywords: ['lac', 'allemagne', 'montagne'] },
    { id: 'n002', url: 'https://i.postimg.cc/4N8922mB/Apple-by-Olivier-Miche-via-unsplash-com.jpg', keywords: ['pomme', 'fruit', 'rouge'] },
    { id: 'n003', url: 'https://i.postimg.cc/FsPLCC7p/Astronaut-by-NASA-via-unsplash-com.jpg', keywords: ['astronaute', 'espace', 'nasa'] },
    { id: 'n004', url: 'https://i.postimg.cc/hP4mrRP1/Books-cards-by-Annie-Spratt-via-unsplash-com.jpg', keywords: ['livres', 'cartes', 'culture'] },
    { id: 'n005', url: 'https://i.postimg.cc/15RFH15G/Bridge-by-Skyler-Smith-via-unsplash-com.jpg', keywords: ['pont', 'architecture', 'passage'] },
    { id: 'n006', url: 'https://i.postimg.cc/xTjmRVTy/Bryce-Canyon-National-Park-Bryce-United-States-by-Drew-Hays-via-unsplash-com.jpg', keywords: ['canyon', 'usa', 'nature'] },
    { id: 'n007', url: 'https://i.postimg.cc/PrfD4nrZ/Canary-Wharf-London-United-Kingdom-by-Annie-Spratt-via-unsplash-com.jpg', keywords: ['ville', 'londres', 'urbain'] },
    { id: 'n008', url: 'https://i.postimg.cc/MKZBDJKT/Cape-Nelson-Lighthouse-Portland-Australia-by-Joshua-Hibbert-via-unsplash-com.jpg', keywords: ['phare', 'australie', 'mer'] },
    { id: 'n009', url: 'https://i.postimg.cc/4N4c5RNX/Cave-in-Malta-by-Simon-Wijers-via-unsplash-com.jpg', keywords: ['grotte', 'malte', 'roche'] },
    { id: 'n010', url: 'https://i.postimg.cc/L64PTF6q/Cedar-Falls-United-States-by-Drew-Hays-via-unsplash-com.jpg', keywords: ['cascade', 'usa', 'eau'] },
    { id: 'n011', url: 'https://i.postimg.cc/gkchDbkY/Chantilly-France-by-Gabriel-Ghnassia-via-unsplash-com.jpg', keywords: ['chateau', 'france', 'histoire'] },
    { id: 'n012', url: 'https://i.postimg.cc/c1BYwLZ4/Coffee-by-Desiree-Fawn-via-unsplash-com.jpg', keywords: ['café', 'repos', 'matin'] },
    { id: 'n013', url: 'https://i.postimg.cc/MZmRVpxp/Compass-by-Jon-Ottosson-via-unsplash-com.jpg', keywords: ['boussole', 'direction', 'voyage'] },
    { id: 'n014', url: 'https://i.postimg.cc/1Rr6w3PR/Computer-by-Dan-Edwards-via-unsplash-com.jpg', keywords: ['ordinateur', 'travail', 'digital'] },
    { id: 'n015', url: 'https://i.postimg.cc/gcHR82d9/Console-by-Patryk-Gradys-via-unsplash-com.jpg', keywords: ['console', 'jeu', 'loisir'] },
    { id: 'n016', url: 'https://i.postimg.cc/Wpwrg1VB/Dominican-Republic-by-Dirk-Sebregts-via-unsplash-com.jpg', keywords: ['plage', 'tropiques', 'vacances'] },
    { id: 'n017', url: 'https://i.postimg.cc/DfPsLwhD/Don-t-just-stand-there-by-Jeff-Sheldon-via-unsplash-com.jpg', keywords: ['mouvement', 'chaussures', 'action'] },
    { id: 'n018', url: 'https://i.postimg.cc/KcDLB8bd/Feet-by-Alex-Wong-via-unsplash-com.jpg', keywords: ['pieds', 'repos', 'humain'] },
    { id: 'n019', url: 'https://i.postimg.cc/hvsdBpMT/Flowering-tree-by-reza-shayestehpour-via-unsplash-com.jpg', keywords: ['arbre', 'fleurs', 'printemps'] },
    { id: 'n020', url: 'https://i.postimg.cc/C57qgmJD/Forrest-bridge-by-Nick-Scheerbart-via-unsplash-com.jpg', keywords: ['forêt', 'pont', 'mystère'] },
    { id: 'n021', url: 'https://i.postimg.cc/rsjrkQgd/Fushimi-Inari-Taisha-Kyoto-Japan-by-freddie-marriage-via-unsplash-com.jpg', keywords: ['japon', 'temple', 'tradition'] },
    { id: 'n022', url: 'https://i.postimg.cc/wM2mp02C/Gaddede-Sweden-by-Jon-Ottosson-via-unsplash-com.jpg', keywords: ['suède', 'nature', 'calme'] },
    { id: 'n023', url: 'https://i.postimg.cc/BbpK0MNf/Gallaryd-Varnamo-O-Sweden-by-Jon-Ottosson-via-unsplash-com.jpg', keywords: ['suède', 'paysage', 'horizon'] },
    { id: 'n024', url: 'https://i.postimg.cc/SRdMhDV2/Glacier-Hikers-by-Claire-Nolan-via-unsplash-com.jpg', keywords: ['glacier', 'marche', 'froid'] },
    { id: 'n025', url: 'https://i.postimg.cc/prCFHqkH/Great-Smoky-Mountains-United-States-by-Rachel-Davis-via-unsplash-com.jpg', keywords: ['montagnes', 'brume', 'usa'] },
    { id: 'n026', url: 'https://i.postimg.cc/4ys9qr60/Hands-by-Desiree-Fawn-via-unsplash-com.jpg', keywords: ['mains', 'union', 'geste'] },
    { id: 'n027', url: 'https://i.postimg.cc/MHqQNh7h/Heliport-by-Jon-Ottosson-via-unsplash-com.jpg', keywords: ['héliport', 'aviation', 'technique'] },
    { id: 'n028', url: 'https://i.postimg.cc/zv8g69CF/Hudson-New-York-United-States-by-Joe-Beck-via-unsplash-com.jpg', keywords: ['hudson', 'ny', 'rivière'] },
    { id: 'n029', url: 'https://i.postimg.cc/nrpDg643/Indiana-United-States-by-Evelyn-Mostrom-via-unsplash-com.jpg', keywords: ['indiana', 'campagne', 'usa'] },
    { id: 'n030', url: 'https://i.postimg.cc/76gzBx2X/Isles-of-Scilly-United-Kingdom-by-Annie-Spratt-via-unsplash-com.jpg', keywords: ['iles', 'uk', 'mer'] },
    { id: 'n031', url: 'https://i.postimg.cc/vBWnPQV7/Kent-United-Kingdom-by-Dan-Edwards-via-unsplash-com.jpg', keywords: ['kent', 'uk', 'paysage'] },
    { id: 'n032', url: 'https://i.postimg.cc/zBnhdJgC/Lake-Louise-Canada-by-Roberto-Nickson-via-unsplash-com.jpg', keywords: ['canada', 'lac', 'bleu'] },
    { id: 'n033', url: 'https://i.postimg.cc/G2kDMcyk/Lassen-Volcanic-National-Park-Mineral-United-States-by-Joshua-Stannard-via-unsplash-com.jpg', keywords: ['parc', 'volcan', 'usa'] },
    { id: 'n034', url: 'https://i.postimg.cc/RFctPMHf/Letters-by-Joanna-Kosinska-via-unsplash-com.jpg', keywords: ['lettres', 'écriture', 'alphabet'] },
    { id: 'n035', url: 'https://i.postimg.cc/4dzc8J9y/Lovers-by-Morgan-Sessions-via-unsplash-com.jpg', keywords: ['amoureux', 'couple', 'amour'] },
    { id: 'n036', url: 'https://i.postimg.cc/sXpWnVhj/Lower-Manhattan-One-World-Trade-Center-New-York-United-States-by-Maxim-Melnikov-via-unsplash-com.jpg', keywords: ['ny', 'gratte-ciel', 'urbain'] },
    { id: 'n037', url: 'https://i.postimg.cc/Qtp76XTd/Man-s-face-Venray-Nederland-by-Simon-Wijers-via-unsplash-com.jpg', keywords: ['visage', 'portrait', 'homme'] },
    { id: 'n038', url: 'https://i.postimg.cc/gJ9Rqwnj/Neuschwanstein-Castle-Schwangau-Germany-by-Rachel-Davis-via-unsplash-com.jpg', keywords: ['chateau', 'allemagne', 'conte'] },
    { id: 'n039', url: 'https://i.postimg.cc/KzXLrKRZ/New-York-United-States-by-Joe-Beck-via-unsplash-com.jpg', keywords: ['ny', 'ville', 'usa'] },
    { id: 'n040', url: 'https://i.postimg.cc/MTkRbcvZ/Norway-by-Marcelo-Quinan-via-unsplash-com.jpg', keywords: ['norvège', 'fjord', 'froid'] },
    { id: 'n041', url: 'https://i.postimg.cc/VN0nC9LQ/Old-camera-by-Annie-Spratt-via-unsplash-com.jpg', keywords: ['appareil photo', 'vintage', 'photo'] },
    { id: 'n042', url: 'https://i.postimg.cc/HxG54JVC/Old-plane-by-Jeff-Sheldon-via-unsplash-com.jpg', keywords: ['avion', 'ancien', 'vol'] },
    { id: 'n043', url: 'https://i.postimg.cc/pd5zFQXt/Parque-Natural-de-Sintra-Cascais-Portugal-by-Manuel-Inglez-via-unsplash-com.jpg', keywords: ['portugal', 'parc', 'nature'] },
    { id: 'n044', url: 'https://i.postimg.cc/rm6WCdzZ/Porto-Portugal-by-Samuel-Zeller-via-unsplash-com.jpg', keywords: ['porto', 'ville', 'couleurs'] },
    { id: 'n045', url: 'https://i.postimg.cc/PqvYwbfb/Railway-by-Andrea-Boldizsar-via-unsplash-com.jpg', keywords: ['train', 'rails', 'voyage'] },
    { id: 'n046', url: 'https://i.postimg.cc/N02mH8Gd/Road-in-Island-by-Jon-Ottosson-via-unsplash-com.jpg', keywords: ['route', 'islande', 'aventure'] },
    { id: 'n047', url: 'https://i.postimg.cc/25LhZdj7/Rock-destination-by-Mathias-Jensen-via-unsplash-com.jpg', keywords: ['roche', 'montagne', 'sommet'] },
    { id: 'n048', url: 'https://i.postimg.cc/FKk3LbFx/Silberkarklamm-Austria-by-Florian-Bernhardt-via-unsplash-com.jpg', keywords: ['autriche', 'rivière', 'roche'] },
    { id: 'n049', url: 'https://i.postimg.cc/6Q4nvV6v/Sirenum-Fossae-Mars-by-NASA-via-unsplash-com.jpg', keywords: ['mars', 'planète', 'espace'] },
    { id: 'n050', url: 'https://i.postimg.cc/wjGDM4zD/Smile-by-Lesly-B-Juarez-via-unsplash-com.jpg', keywords: ['sourire', 'joie', 'femme'] },
    { id: 'n051', url: 'https://i.postimg.cc/DwM10phJ/Sparks-by-Morgan-Sessions-via-unsplash-com.jpg', keywords: ['étincelles', 'feu', 'énergie'] },
    { id: 'n052', url: 'https://i.postimg.cc/mg57kp4S/Stockholm-Sweden-by-Jon-Ottosson-via-unsplash-com.jpg', keywords: ['stockholm', 'ville', 'eau'] },
    { id: 'n053', url: 'https://i.postimg.cc/kgpWGYCD/Strom-by-NASA-via-unsplash-com.jpg', keywords: ['tempête', 'espace', 'nuages'] },
    { id: 'n054', url: 'https://i.postimg.cc/cLbfCkW1/Subway-New-York-by-Brooke-Cagle-via-unsplash-com.jpg', keywords: ['métro', 'ny', 'foule'] },
    { id: 'n055', url: 'https://i.postimg.cc/8z0LcXGP/Swing-by-Aaron-Burden-via-unsplash-com.jpg', keywords: ['balançoire', 'enfance', 'liberté'] },
    { id: 'n056', url: 'https://i.postimg.cc/6p3d9Jk5/Tallebudgera-Creek-Australia-by-Christopher-Campbell-via-unsplash-com.jpg', keywords: ['rivière', 'australie', 'calme'] },
    { id: 'n057', url: 'https://i.postimg.cc/W1H0zYVv/Team-spirit-by-Olga-Guryanova-via-unsplash-com.jpg', keywords: ['équipe', 'groupe', 'sport'] },
    { id: 'n058', url: 'https://i.postimg.cc/Gm2kcwWb/Teriberka-Russia-by-Paul-Itkin-via-unsplash-com.jpg', keywords: ['russie', 'mer', 'froid'] },
    { id: 'n059', url: 'https://i.postimg.cc/nhPqrSxt/The-Fulton-Center-New-York-United-States-by-Michael-Fernandez-via-unsplash-com.jpg', keywords: ['architecture', 'ny', 'lumière'] },
    { id: 'n060', url: 'https://i.postimg.cc/T3wrRMz8/Ukraine-by-Paul-Itkin-via-unsplash-com.jpg', keywords: ['ukraine', 'ville', 'histoire'] },
    { id: 'n061', url: 'https://i.postimg.cc/L8XzHKrc/Valley-by-Jeff-Sheldon-via-unsplash-com.jpg', keywords: ['vallée', 'nature', 'horizon'] },
    { id: 'n062', url: 'https://i.postimg.cc/13tp9hLL/Venray-Nederland-by-Simon-Wijers-via-unsplash-com.jpg', keywords: ['pays-bas', 'ville', 'calme'] },
    { id: 'n063', url: 'https://i.postimg.cc/wjvh68S0/Wind-turbines-by-Andrea-Boldizsar-via-unsplash-com.jpg', keywords: ['éoliennes', 'énergie', 'futur'] },
    { id: 'n064', url: 'https://i.postimg.cc/YC91pKJn/Winter-bath-by-Jeff-Sheldon-via-unsplash-com.jpg', keywords: ['hiver', 'froid', 'eau'] },
];

const PERSPECTIVES_PHOTOS: Photo[] = [
    { id: 'p001', url: 'https://i.postimg.cc/D0mmsnnx/1496519447.jpg', keywords: ['travail', 'groupe', 'bureau'] },
    { id: 'p002', url: 'https://i.postimg.cc/0jrrmPP7/19-1-nf-formation-agro-gms.jpg', keywords: ['industrie', 'formation', 'agro'] },
    { id: 'p003', url: 'https://i.postimg.cc/XqXXF44k/219953747-small.jpg', keywords: ['science', 'microscope', 'recherche'] },
    { id: 'p004', url: 'https://i.postimg.cc/NFLLTBB8/22914.jpg', keywords: ['plan', 'architecture', 'technique'] },
    { id: 'p005', url: 'https://i.postimg.cc/PJNNZTTm/26-jerash-xl.jpg', keywords: ['histoire', 'ruines', 'voyage'] },
    { id: 'p006', url: 'https://i.postimg.cc/pryy8RRf/4-enfants.jpg', keywords: ['enfance', 'partage', 'sourire'] },
    { id: 'p007', url: 'https://i.postimg.cc/7hbb7wwN/582-Troopers-receiving-information-about-next-competition.jpg', keywords: ['stratégie', 'briefing', 'équipe'] },
    { id: 'p008', url: 'https://i.postimg.cc/3NWWpYYB/86206235-small.jpg', keywords: ['abstrait', 'bleu', 'texture'] },
    { id: 'p009', url: 'https://i.postimg.cc/fykkXDDq/Affiche-egalite2.jpg', keywords: ['égalité', 'social', 'affiche'] },
    { id: 'p010', url: 'https://i.postimg.cc/Fz11cNNW/afficher-image.jpg', keywords: ['art', 'cadre', 'peinture'] },
    { id: 'p011', url: 'https://i.postimg.cc/brMr9WwH/alex.jpg', keywords: ['portrait', 'jeune', 'regard'] },
    { id: 'p012', url: 'https://i.postimg.cc/hvhhxccC/Alex-Grigny-de-Castro-Sojourner-Large.jpg', keywords: ['robotique', 'mars', 'exploration'] },
    { id: 'p013', url: 'https://i.postimg.cc/90S0YKQB/alex-ii-imp-maria-alex-25marriage.jpg', keywords: ['histoire', 'mariage', 'noblesse'] },
    { id: 'p014', url: 'https://i.postimg.cc/cCjCB2Lm/aleximg.jpg', keywords: ['portrait', 'visage', 'homme'] },
    { id: 'p015', url: 'https://i.postimg.cc/GtNtxVmM/Animation-magasin.jpg', keywords: ['commerce', 'animation', 'public'] },
    { id: 'p016', url: 'https://i.postimg.cc/NFVFkSjC/ap17-72-H-314.jpg', keywords: ['espace', 'lune', 'apollo'] },
    { id: 'p017', url: 'https://i.postimg.cc/6qSqfgp1/Artistes-140-2002-06-5-musiciens-copier.jpg', keywords: ['musique', 'concert', 'groupe'] },
    { id: 'p018', url: 'https://i.postimg.cc/nr5rGghg/atf19.jpg', keywords: ['mécanique', 'avion', 'moteur'] },
    { id: 'p019', url: 'https://i.postimg.cc/Y0V0zZCP/ballade-cormet-rosseland-aou00.jpg', keywords: ['montagne', 'randonnée', 'nature'] },
    { id: 'p020', url: 'https://i.postimg.cc/mkqkyJgq/bassiak.jpg', keywords: ['afrique', 'portrait', 'expression'] },
    { id: 'p021', url: 'https://i.postimg.cc/7hchndZj/berger.jpg', keywords: ['berger', 'moutons', 'campagne'] },
    { id: 'p022', url: 'https://i.postimg.cc/7hchndL8/bomba01.jpg', keywords: ['machine', 'outil', 'technique'] },
    { id: 'p023', url: 'https://i.postimg.cc/5yGySTtW/boulanger-121-tcm41-7294.jpg', keywords: ['boulanger', 'métier', 'pain'] },
    { id: 'p024', url: 'https://i.postimg.cc/GtNtxVpC/c172.jpg', keywords: ['aviation', 'vol', 'cockpit'] },
    { id: 'p025', url: 'https://i.postimg.cc/j2924mjr/chef-M-Stadtlander.jpg', keywords: ['cuisine', 'chef', 'gastronomie'] },
    { id: 'p026', url: 'https://i.postimg.cc/D0D0PHz2/competition-LFS-2005-(67).jpg', keywords: ['sport', 'course', 'école'] },
    { id: 'p027', url: 'https://i.postimg.cc/FzqzV8Kr/conducteur.jpg', keywords: ['camion', 'route', 'conduite'] },
    { id: 'p028', url: 'https://i.postimg.cc/qBZNrhxN/CONVAR93.jpg', keywords: ['discours', 'congrès', 'politique'] },
    { id: 'p029', url: 'https://i.postimg.cc/c15vWgBw/Cours-Vigneux.jpg', keywords: ['classe', 'école', 'apprentissage'] },
    { id: 'p030', url: 'https://i.postimg.cc/XNDrWGkD/cuisine.jpg', keywords: ['cuisine', 'groupe', 'repas'] },
    { id: 'p031', url: 'https://i.postimg.cc/NGPKt9kk/danse.jpg', keywords: ['danse', 'ballet', 'spectacle'] },
    { id: 'p032', url: 'https://i.postimg.cc/2jX1Yb74/digitaldrucke1.jpg', keywords: ['technologie', 'impression', 'numérique'] },
    { id: 'p033', url: 'https://i.postimg.cc/VsHJwrWR/divan-japonais-maitre-web.jpg', keywords: ['affiche', 'art', 'cabaret'] },
    { id: 'p034', url: 'https://i.postimg.cc/9XND2RYB/diver.jpg', keywords: ['plongée', 'mer', 'exploration'] },
    { id: 'p035', url: 'https://i.postimg.cc/FFnYvdVB/dre117.jpg', keywords: ['électricité', 'câbles', 'technique'] },
    { id: 'p036', url: 'https://i.postimg.cc/CM6R0Bs2/DSCN3859.jpg', keywords: ['nature', 'macro', 'insecte'] },
    { id: 'p037', url: 'https://i.postimg.cc/h43Xnz16/equipe-spv-pt.jpg', keywords: ['pompiers', 'équipe', 'secours'] },
    { id: 'p038', url: 'https://i.postimg.cc/Y2yv7GzT/Ernest-Lavisse14-1.jpg', keywords: ['histoire', 'école', 'maître'] },
    { id: 'p039', url: 'https://i.postimg.cc/15nf3mvJ/escalier.jpg', keywords: ['escalier', 'monument', 'architecture'] },
    { id: 'p040', url: 'https://i.postimg.cc/gcBxpXHf/forme.jpg', keywords: ['géométrie', 'design', 'art'] },
    { id: 'p041', url: 'https://i.postimg.cc/m2ztgLmd/fouille.jpg', keywords: ['archéologie', 'histoire', 'recherche'] },
    { id: 'p042', url: 'https://i.postimg.cc/VLrdkfKG/francais.jpg', keywords: ['dictionnaire', 'livre', 'langue'] },
    { id: 'p043', url: 'https://i.postimg.cc/3J4dx8tV/garde.jpg', keywords: ['garde', 'palais', 'uniforme'] },
    { id: 'p044', url: 'https://i.postimg.cc/vHgcZY0S/grandeur.jpg', keywords: ['paysage', 'immensité', 'nature'] },
    { id: 'p045', url: 'https://i.postimg.cc/CLBzxhc2/H2H19Endings-Mike.jpg', keywords: ['relais', 'sport', 'passage'] },
    { id: 'p046', url: 'https://i.postimg.cc/PrpP5XSc/HHTRUMP.jpg', keywords: ['trompette', 'jazz', 'musique'] },
    { id: 'p047', url: 'https://i.postimg.cc/DyJ8wvxt/imag12mare.jpg', keywords: ['mer', 'plage', 'vacances'] },
    { id: 'p048', url: 'https://i.postimg.cc/HnKn9RLW/image.jpg', keywords: ['lac', 'montagne', 'reflet'] },
    { id: 'p049', url: 'https://i.postimg.cc/fTtJRzHZ/Image128.gif', keywords: ['ordinateur', 'ancien', 'écran'] },
    { id: 'p050', url: 'https://i.postimg.cc/5NY624PV/Image7.jpg', keywords: ['biologie', 'cellule', 'recherche'] },
    { id: 'p051', url: 'https://i.postimg.cc/CLBzxhvF/Initiation-escalade-Pont-de-Montvert.jpg', keywords: ['escalade', 'sport', 'initiation'] },
    { id: 'p052', url: 'https://i.postimg.cc/Gh8HmLMb/kapalicarsi-musique01.jpg', keywords: ['musique', 'tradition', 'orient'] },
    { id: 'p053', url: 'https://i.postimg.cc/rF0KwVhy/Kwi-Krimp-600.jpg', keywords: ['outil', 'industrie', 'machine'] },
    { id: 'p054', url: 'https://i.postimg.cc/m2ztgLdt/Learning-to-Surf.jpg', keywords: ['surf', 'apprentissage', 'mer'] },
    { id: 'p055', url: 'https://i.postimg.cc/bNDswy6Z/lecture.jpg', keywords: ['lecture', 'étudiant', 'livre'] },
    { id: 'p056', url: 'https://i.postimg.cc/5NhjHhGb/liqing-pool.jpg', keywords: ['billard', 'loisir', 'jeu'] },
    { id: 'p057', url: 'https://i.postimg.cc/bN7dG7Mq/Livre.jpg', keywords: ['livre', 'page', 'lecture'] },
    { id: 'p058', url: 'https://i.postimg.cc/Kv64K6Vj/livres.jpg', keywords: ['bibliothèque', 'culture', 'savoir'] },
    { id: 'p059', url: 'https://i.postimg.cc/fTGk3GFb/LSM-ribaud.jpg', keywords: ['portrait', 'noir et blanc', 'expression'] },
    { id: 'p060', url: 'https://i.postimg.cc/c4p6KpjH/lun.jpg', keywords: ['lune', 'astronomie', 'nuit'] },
    { id: 'p061', url: 'https://i.postimg.cc/8P2sF23j/maitre.jpg', keywords: ['maître', 'leçon', 'école'] },
    { id: 'p062', url: 'https://i.postimg.cc/xTwqkw7b/maitre-tamura.jpg', keywords: ['arts martiaux', 'maître', 'aikido'] },
    { id: 'p063', url: 'https://i.postimg.cc/tCK71KfW/manuel.jpg', keywords: ['travail', 'manuel', 'mains'] },
    { id: 'p064', url: 'https://i.postimg.cc/Qx2VB2P9/metre-etalon.jpg', keywords: ['mesure', 'règle', 'science'] },
    { id: 'p065', url: 'https://i.postimg.cc/HsqjJqKJ/navette.jpg', keywords: ['navette', 'espace', 'vol'] },
    { id: 'p066', url: 'https://i.postimg.cc/VLx5SxTM/nom3cut.jpg', keywords: ['portrait', 'visage', 'profil'] },
    { id: 'p067', url: 'https://i.postimg.cc/bN7dG7M9/Panneau-vue.gif', keywords: ['vision', 'vue', 'ophtalmologie'] },
    { id: 'p068', url: 'https://i.postimg.cc/CL3dZ3t4/panneaux-thai.jpg', keywords: ['signalisation', 'thaïlande', 'rue'] },
    { id: 'p069', url: 'https://i.postimg.cc/pXwy9w7C/part02.jpg', keywords: ['musique', 'partition', 'notes'] },
    { id: 'p070', url: 'https://i.postimg.cc/4NDnKDMB/paulrobert.jpg', keywords: ['livre', 'dictionnaire', 'savoir'] },
    { id: 'p071', url: 'https://i.postimg.cc/nhqrqdb7/pedagogie-active.jpg', keywords: ['pédagogie', 'groupe', 'travail'] },
    { id: 'p072', url: 'https://i.postimg.cc/vZ5T5PFP/photolangage.jpg', keywords: ['mains', 'cartes', 'choix'] },
    { id: 'p073', url: 'https://i.postimg.cc/7ZShSB8g/Porte5.jpg', keywords: ['porte', 'bois', 'entrée'] },
    { id: 'p074', url: 'https://i.postimg.cc/g23j3MFq/prec-1.jpg', keywords: ['technique', 'précision', 'outil'] },
    { id: 'p075', url: 'https://i.postimg.cc/fRYyYHnc/precision.jpg', keywords: ['horlogerie', 'montre', 'précision'] },
    { id: 'p076', url: 'https://i.postimg.cc/kgWGWj3y/rencontre-cle0145ba-3.jpg', keywords: ['accord', 'politique', 'mains'] },
    { id: 'p077', url: 'https://i.postimg.cc/rw5s5hXj/riziere6.jpg', keywords: ['rizière', 'agriculture', 'terre'] },
    { id: 'p078', url: 'https://i.postimg.cc/P51J16s4/rythmeos.jpg', keywords: ['rythme', 'son', 'vibration'] },
    { id: 'p079', url: 'https://i.postimg.cc/7ZShSB8s/salle-permanence.jpg', keywords: ['école', 'étude', 'salle'] },
    { id: 'p080', url: 'https://i.postimg.cc/2SnynHRt/schmids3c.jpg', keywords: ['portrait', 'visage', 'homme'] },
    { id: 'p081', url: 'https://i.postimg.cc/g23j3MF5/sesia-mollia-sco-(14).jpg', keywords: ['rivière', 'eau', 'nature'] },
    { id: 'p082', url: 'https://i.postimg.cc/Bn2b2hfW/SIEBUS.jpg', keywords: ['bus', 'transport', 'ville'] },
    { id: 'p083', url: 'https://i.postimg.cc/x1L8LsVV/solitude.jpg', keywords: ['solitude', 'banc', 'penseur'] },
    { id: 'p084', url: 'https://i.postimg.cc/GmvtvMwZ/suivi-traces.jpg', keywords: ['neige', 'traces', 'chemin'] },
    { id: 'p085', url: 'https://i.postimg.cc/FH0z0PX5/Surgeons-Looking-at-Patient.jpg', keywords: ['médecine', 'chirurgie', 'hôpital'] },
    { id: 'p086', url: 'https://i.postimg.cc/7LD69gwW/tableau-jeu.jpg', keywords: ['jeu', 'école', 'classe'] },
    { id: 'p087', url: 'https://i.postimg.cc/HLHxzQdK/testing-6sn7gt.gif', keywords: ['test', 'lampe', 'électronique'] },
    { id: 'p088', url: 'https://i.postimg.cc/W4j38MsR/thai-corn-cake-david-hand.jpg', keywords: ['cuisine', 'thaïlande', 'marché'] },
    { id: 'p089', url: 'https://i.postimg.cc/VN16gjQ/Tourbillon-de-sable-img4904.jpg', keywords: ['désert', 'vent', 'sable'] },
    { id: 'p090', url: 'https://i.postimg.cc/8CD54hNx/tourbillon10.jpg', keywords: ['mouvement', 'spirale', 'abstrait'] },
    { id: 'p091', url: 'https://i.postimg.cc/VN16gj8/tres-ranchos-canoe.jpg', keywords: ['canoë', 'sport', 'rivière'] },
    { id: 'p092', url: 'https://i.postimg.cc/TPGw0rTX/tribunal.jpg', keywords: ['justice', 'loi', 'tribunal'] },
    { id: 'p093', url: 'https://i.postimg.cc/Xv3JLwnV/tu-dresden-slub-lesesaal-studenten-02.jpg', keywords: ['bibliothèque', 'université', 'travail'] },
    { id: 'p094', url: 'https://i.postimg.cc/43ZdPzXZ/union10.jpg', keywords: ['union', 'mains', 'groupe'] },
    { id: 'p095', url: 'https://i.postimg.cc/Xv3JLwnn/vendanges.gif', keywords: ['vigne', 'tradition', 'travail'] },
    { id: 'p096', url: 'https://i.postimg.cc/KYFzfnm8/Web-Contest1.jpg', keywords: ['monde', 'réseau', 'internet'] },
    { id: 'p097', url: 'https://i.postimg.cc/Xv3JLwn7/yak50panel.jpg', keywords: ['aviation', 'instrument', 'cockpit'] },
    { id: 'p098', url: 'https://i.postimg.cc/g0dJsvG0/zdrag-full.jpg', keywords: ['mouvement', 'vitesse', 'abstrait'] },
    { id: 'p099', url: 'https://i.postimg.cc/hvhhxccd/zenith.jpg', keywords: ['soleil', 'ciel', 'zénith'] },
];

export const PHOTO_FOLDERS: PhotoFolder[] = [
  {
    id: 'yapaka',
    name: 'Yapaka - Photo Expression',
    description: 'La collection intégrale de 112 photos Yapaka pour libérer la parole.',
    cover: 'https://i.postimg.cc/wBNzrtbq/112.jpg',
    photos: YAPAKA_PHOTOS
  },
  {
    id: 'perspectives',
    name: 'Société & Perspectives',
    description: 'Une collection de 99 images explorant les dynamiques sociales et professionnelles.',
    cover: 'https://i.postimg.cc/0jrrmPP7/19-1-nf-formation-agro-gms.jpg',
    photos: PERSPECTIVES_PHOTOS
  },
  {
    id: 'pedagogie',
    name: 'Pédagogie & Monde',
    description: 'Images axées sur l\'apprentissage, le travail et la découverte.',
    cover: 'https://i.postimg.cc/nhqrqdb7/pedagogie-active.jpg',
    photos: PERSPECTIVES_PHOTOS 
  },
  {
    id: 'inspiration',
    name: 'Inspiration & Nature',
    description: '64 images évocatrices de paysages pour stimuler l\'imagination.',
    cover: 'https://i.postimg.cc/zBnhdJgC/Lake-Louise-Canada-by-Roberto-Nickson-via-unsplash-com.jpg',
    photos: INSPIRATION_PHOTOS
  }
];

export const SESSION_TEMPLATES: SessionTemplate[] = [
    {
        id: 'libre',
        title: 'Séance Libre',
        description: 'Créez votre séance à partir de la collection Yapaka.',
        question: 'Choisissez une image qui vous interpelle...',
        defaultFolderId: 'yapaka',
        icon: 'Edit3'
    },
    {
        id: 'meteo',
        title: 'Météo Intérieure',
        description: 'Démarrer une réunion avec la collection Yapaka.',
        question: 'Quelle image correspond le mieux à votre état d\'esprit actuel ?',
        defaultFolderId: 'yapaka',
        icon: 'Sun'
    },
    {
        id: 'perspectives-societe',
        title: 'Société & Perspectives',
        description: 'Utiliser la collection de 99 images sur le travail et la vie en société.',
        question: 'Quelle image illustre le mieux un défi de notre époque ?',
        defaultFolderId: 'perspectives',
        icon: 'Globe'
    }
];

export const MOCK_PHOTOS = YAPAKA_PHOTOS;
export const INITIAL_SESSION_CODE = "XJ9-2B";
